### ISSUE TITLE
radarIP

### ISSUE THREAD

**Issue by hanjun815** [robotics-upo/ars548_ros#3]
We're going to install a driver in ros noetic.
How do I set the radarIP part in the ars548_launch.launch file?

<arg name="radarIP" default="224.0.2.2"/>
<arg name="radarPort" default="42102"/>

**Comment by david-alejo** [comment]
Dear Hanjun,

You can modify the RadarIP to which the driver tries to connect simply by overriding it when calling the launch:

> roslaunch ars548_driver ars548_launch.launch radarIP:=224.0.0.2

However, we don't recommend you to modify the radarIP neither the radarPort, as they are set to the default values of the RADAR.

The point is that you probably will have to configure a VLAN connection so that you can connect to the radar.

For that, please follow the instructions on the README.md. You can also find the instructions on the following video:

https://youtu.be/vByzrxY0N2k

Please let us know if you could configure the RADAR properly. 

Best regards,

David

**Comment by hanjun815** [comment]
Dear David,

Thank you for your kind information. The problem has been resolved.
Have a nice day.

Thank you.

Best regards,
Hanjun

2024년 7월 8일 (월) 오후 5:47, David Alejo Teissière ***@***.***>님이
작성:

**Comment by david-alejo** [comment]
Dear Hanjun,

I'm very pleased to hear the good news! 

I'm proceeding to close the issue then.

Thank you very much for your response. 

Best regards,

David
